##LOGIN
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "abc@email.com",
  "password": "123456"
}

### GET PROFILE / TOKEN TEST
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTc5MDU4NjkxOSwiZXhwIjoxNzkwNTkwNTE5fQ.O6wdXPzvwjkPAc4nN-AAHa5PajiyEnghLysOKvJFEvI

###REGISTER USER BARU
POST http://localhost:3000/api/auth/register
Content-Type : application/json

{
  "nama" : "zikri",
  "email": "zikri@email.com",
  "password": "zikri123"
}


###menambahkan profil
POST http://localhost:3000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTc5MDU4NzEyOSwiZXhwIjoxNzkwNTkwNzI5fQ.I0PFCpoLMozDjxDjUa7ifSSko_zs_sRvSQklWwiSXEc
Content-Type: application/json

{
  "bio": "Halo, saya sedang belajar membuat fitur About Me.",
  "pendidikan": "S1 Ilmu Komputer",
  "hobi": "Ngoding dan Olahraga",
  "kontak": "08123456789"
}